model_train_type = "flux-lora"
pretrained_model_name_or_path = "/content/models/unet/flux1-dev-fp8.safetensors"
ae = "/content/models/vae/ae.safetensors"
clip_l = "/content/models/text_encoders/clip_l.safetensors"
t5xxl = "/content/models/text_encoders/t5xxl_fp8_e4m3fn.safetensors"
timestep_sampling = "sigmoid"
sigmoid_scale = 1
model_prediction_type = "raw"
discrete_flow_shift = 1
loss_type = "l2"
guidance_scale = 1
train_t5xxl = false
train_data_dir = "/content/drive/MyDrive/xiaoen"
prior_loss_weight = 1
resolution = "512,512"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "aki"
output_dir = "/content/drive/MyDrive/xiaoen-o"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 1
save_state = true
max_train_epochs = 20
train_batch_size = 1
gradient_checkpointing = true
gradient_accumulation_steps = 1
network_train_unet_only = true
network_train_text_encoder_only = false
learning_rate = 0.0001
unet_lr = 0.0001
text_encoder_lr = 0.00001
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 0
lr_scheduler_num_cycles = 1
optimizer_type = "AdamW8bit"
network_module = "networks.lora_flux"
network_dim = 2
network_alpha = 16
randomly_choice_prompt = false
positive_prompts = "masterpiece, best quality, 1girl, solo"
negative_prompts = "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry"
sample_width = 512
sample_height = 512
sample_cfg = 7
sample_seed = 2333
sample_steps = 20
sample_sampler = "euler"
sample_every_n_epochs = 1
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 0
seed = 1337
clip_skip = 2
mixed_precision = "bf16"
sdpa = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
persistent_data_loader_workers = true
fp8_base = true
